baseurl = "http://innovatelb.com/CIS-2016"
languageCode = "en-us"
title = "CIS 2016"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All events of the speakers are defined in their own files.
	# You can events at 'data/speakers'.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Long Beach Civic Innovation Summit"
	description = "Recognizing outstanding innovation in government."

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "City of Long Beach"

		[params.navigation.links]
			register 	= "Register"
			cost     	= "Cost"
			attendees = "Attendees"
			speakers 	= "Speakers"
			where 		= "Where"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		# To chanve the logo of the hero section, replace the image at 'layouts/partials/hero.html' with your own.
		# It's best to define an all-white and colored logo in the creative.css

		description	= "The City of Long Beach is a national leader in civic, social, and government innovation. This day-long summit, sponsored by the City of Long Beach, is an opportunity for thought leaders, community members, planners, and professional staff to recognize outstanding efforts and cutting-edge innovation in the public sector."
		buttonText 	= "Register Now"

	[params.register]
		headline   	= "Will you be attending?"

	# Cost section
	[params.cost]
		headline    = "How much does it cost?"
		description = "There is no cost to participate but space is limited.  Registration will be closed on October 3rd @ 5:00 p.m., or when participation has reached its capacity at 250.  Parking at the Convention Center is $10."
		buttonText  = "Get started!"


	# Attendees section
	[params.attendees]
		headline = "Who should attend?"

    [[params.attendees.list]]
      icon = "fa-users"
      title = "Government employees"
      description = "Local government professionals, managers, and City staff."

    [[params.attendees.list]]
			icon = "fa-institution"
			title = "City Officials"
			description = "City commissioners, City Council members and staff."

		[[params.attendees.list]]
      icon = "fa-graduation-cap"
      title = "Universities"
      description = "University faculty and students interested in public administration, public policy, design thinking, government technology, business administration, and innovation."

    [[params.attendees.list]]
    	icon = "fa-smile-o"
      title = "Community"
    	description = "Community members interested in civic and social innovation"

  	[[params.attendees.list]]
  		icon = "fa-briefcase"
  		title = "Businesses"
  		description = "Entrepreneurs, business owners, and industry leaders interested in ways to partner with local government to make life better for communities."

  # Speakers modals
	[params.speakers.modal]
	  buttonText	= "Close"

	# Speakers section
	[params.speakers]
		headline	= "Speakers"

  # Aside section
	[params.aside]
		headline = "Gain insights from these amazing speakers at the Innovation Summit!"

		[params.aside.button]
			text = "Register now"
			link = "#register"

	# Where sections
	[params.where]
		headline    = "How do I get there?"
		description = "The Seaside Ballroom is at street level on the north side of the Center campus, with a convenient parking turnout and entrance on Seaside Way, and easy access to the Terrace Theater and Plaza, the Arena and the exhibit halls’ north entrance doors. Parking is $10 per car per entry to any of the Convention Center lots."

	# Contact section
	[params.contact]
		headline = "Have something to say?"
		description = "Want to present at the Civic Innovation Summit or have any questions? That's great! Give us a call or send us an email and we will get back to you as soon as possible."
		phone = "562-570-7960"
		email = "i-team@longbeach.gov"
